name: docker build

on:
  push:
    branches: [main]

jobs:
  check-pep440:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    outputs:
      version: ${{ steps.get-version.outputs.PEP440_VERSION }}

    steps:
      - id: get-version
        run: |
          PEP440_VERSION=""
          VERSION_PREFIX="v"
          BRANCH_OR_TAG="$(echo '${{ github.event.ref }}' | cut -d / -f 3)"
          if [[ "${version}" =~ ^v?(([1-9][0-9]*!)?(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*((a|b|rc)(0|[1-9][0-9]*))?(\.post(0|[1-9][0-9]*))?(\.dev(0|[1-9][0-9]*))?)$ ]]
          then
            PEP440_VERSION="${BRANCH_OR_TAG#$VERSION_PREFIX}"
          fi
          echo ::set-output name=version::${PEP440_VERSION}

  build:
    runs-on: ubuntu-latest
    needs: check-pep440
    if: github.event_name == 'push' && needs.check-pep440.outputs.version != ''

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          cache: "pip"

      - name: Install dependencies
        run: pip install build

      - name: Build Python distribution
        run: pyproject-build

      - name: Upload dist to artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist

  publish-pypi:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download dist from artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish-docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download dist from artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pipdot:${{ needs.check-pep440.outputs.version }}
